#!/bin/sh

#  Description:
#
# Simple tool to prepare chboot-part-roller files
#


die(){
	echo "$1" >&2
	exit 1
}

error_msg(){
	MSG_TIT="Error"
	MSG_TXT="$1"
	[ -z "$2" ] || MSG_TIT="$2"
	die "${MSG_TIT}: $MSG_TXT"
}

usage(){
	die "Usage: $(basename "$0") {mkinitrd|gengrub|saveusers|savefiles} CHBOOT_BASE_DIR"
}

get_disk_id(){
	MOUNT_POINT="$1"
	ID_TYPE="$2"
	lsblk -nplo MOUNTPOINT,$ID_TYPE |sed -ne "\%$MOUNT_POINT\s%{s%^.*\s%%;p}"
}

get_uuid(){
	MOUNT_POINT="$1"
	ID_TYPE="UUID"
	get_disk_id "$MOUNT_POINT" "$ID_TYPE"
}

get_partuuid(){
	MOUNT_POINT="$1"
	ID_TYPE="PARTUUID"
	get_disk_id "$MOUNT_POINT" "$ID_TYPE"
}

gen_grub_cfg(){
	CHBOOT_DIR="$1"
	CHBOOT_IMG_NAME="$2"
	CHBOOT_URL="$3"
	BOOT_DIR="$1/boot"
	pkgdatadir=/usr/lib/grub
	GRUB_THEME=""
	GRUB_DISABLE_RECOVERY=true
	GRUB_DISABLE_SUBMENU=true
	# . /etc/grub.d/00_header

	[ "$CHBOOT_TITLE" ] || CHBOOT_TITLE="Unattended LliureX 25 install from DISK image"
	CHBOOT_URL_OPTION=""
	# find chboot initrd
	CHBOOT_INITRD=""

	#echo "Find initrd chboot ..."

	CHBOOT_INITRD="$(ls -1 "$BOOT_DIR" | grep "^initrd_chboot.img" |tail -1)"
	[ "$CHBOOT_INITRD" ] || error_msg "chboot initrd file not found"

	KERNEL_VERSION="${CHBOOT_INITRD#*-}"

	# find chboot partition
	CHBOOT_BY_LABEL="/dev/disk/by-label/chboot"
	[ -e "$CHBOOT_BY_LABEL" ] || error_msg "chboot UUID not found"
	CHBOOT_PART="$(readlink -f "$CHBOOT_BY_LABEL")"
	CHBOOT_UUID="$(lsblk -nplo UUID "$CHBOOT_PART")"

	# find current root partition
	ROOT_UUID="$(get_uuid "/")"
	ROOT_PARTUUID="$(get_partuuid "/")"
	if [ -z "$ROOT_UUID" ] || [ -z "$ROOT_PARTUUID" ] ; then
		error_msg "ROOT partition UUID or PARTUUID not found"
	fi

	# find efi partition
	EFI_UUID="$(get_uuid "/boot/efi")"
	[ "$EFI_UUID" ] || error_msg "EFI UUID not found"
	BOOT_MOUNT_POINT="$(df "$BOOT_DIR" | tail -1 |sed -e "s%^.*\s%%")"
	BOOT_PATH="$(echo "${BOOT_DIR#$BOOT_MOUNT_POINT}" |sed -e "s%/$%%")"
	
	[ "$BOOT_PATH" ] || error_msg "BOOT path not found"
	CHBOOT_PATH="$(echo "${CHBOOT_DIR#$BOOT_MOUNT_POINT}" |sed -e "s%/$%%")"
	[ "$CHBOOT_PATH" ] || error_msg "CHBOOT path not found"

	echo "Generate grub.cfg ..."
	mkdir -p "$BOOT_DIR/grub"
	GRUB_CFG="$BOOT_DIR/grub/grub.cfg"

	CHBOOT_IMG_DIR="$(echo "${CHBOOT_DIR}" |sed -e "s%/srcs/.*$%/imgs%")"
	CHBOOT_IMG_PATH="$(echo "${CHBOOT_IMG_DIR#$BOOT_MOUNT_POINT}" |sed -e "s%/$%%")"
	[ "$CHBOOT_IMG_PATH" ] || error_msg "CHBOOT image path not found"

	if [ "$CHBOOT_IMG_NAME" ] ; then
		CHBOOT_IMG_OPTION="chb.imgname=$CHBOOT_IMG_NAME"
	fi

	chboot_entry > "$GRUB_CFG"
	if [ "$CHBOOT_URL" ] ; then
		# generate alternative entry
		CHBOOT_URL_OPTION="chb.url=$CHBOOT_URL"
		chboot_entry >>  "$GRUB_CFG"
	fi
}

chboot_entry(){
	
	cat <<EOF
set timeout=10
search --no-floppy --fs-uuid --set=root ${CHBOOT_UUID}

menuentry 'CHBOOT: ${CHBOOT_TITLE} (${KERNEL_VERSION})' --class lliurex --class gnu-linux --class gnu --class os \$menuentry_id_option 'gnulinux-${KERNEL_VERSION}-advanced-${ROOT_UUID}' {
        # recordfail
        # load_video
        # gfxmode \$linux_gfx_mode
        insmod gzio
        if [ x\$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
        insmod part_gpt
        insmod ext2
        search --no-floppy --fs-uuid --set=root ${CHBOOT_UUID}
        echo    'Loading Linux ${KERNEL_VERSION} for CHBOOT RESTORE ...'
        linux   ${BOOT_PATH}/vmlinuz-${KERNEL_VERSION} root=PARTUUID=${ROOT_PARTUUID} ro boot=chboot chb.ncurses chb.uuid=${ROOT_UUID} chb.efi=UUID=${EFI_UUID} chb.dev=UUID=${CHBOOT_UUID} chb.dir=${CHBOOT_PATH} chb.imgdir=${CHBOOT_IMG_PATH}  $CHBOOT_IMG_OPTION $CHBOOT_URL_OPTION net.ifnames=0 rw $vt_handoff
        echo    'Loading initial ramdisk ...'
        initrd  ${BOOT_PATH}/${CHBOOT_INITRD}
}

search --no-floppy --fs-uuid --set=oldroot ${ROOT_UUID}
if [ -e (\$oldroot)/boot/grub/grub.cfg ] ; then
	menuentry 'Run old grub configuration to start LliureX' {
		configfile (\$oldroot)/boot/grub/grub.cfg 
	}
fi

EOF
}

install_boot_files(){
	BOOT_DIR="$1"
	#echo "Create initrd and copy kernel to chboot boot dir ..."
	rc=0
	mkdir -p "$BOOT_DIR"
	mkinitramfs -d "$INITRAMFS_DIR"  -o $BOOT_DIR/initrd_chboot.img-$(uname -r) || rc=$?
	[ $rc -ne 0 ] || cp /boot/vmlinuz-$(uname -r) $BOOT_DIR/ || ec=$?
	return $rc
}

preserve_files(){
	FILE_LIST="$1"
	DEST_DIR="$2/files"
	mkdir -p "$DEST_DIR"
	#DEST_DIR="$CHBOOT_DIR/files"
	#echo "Preserve files from $FILE_LIST ..."
	if [ -z "$FILE_LIST" ] || [ ! -s "$FILE_LIST" ] ; then
		return 0
	fi
	rm -fr "$DEST_DIR"

	mkdir -p "$DEST_DIR"
	rsync -a --files-from=$FILE_LIST / "$DEST_DIR" || error_msg "Unable to preserve files"

	# echo "Preserve tags ..."
	TAGS_DIR_LIST="/etc/lliurex-auto-upgrade/tags"

	for d in $TAGS_DIR_LIST ; do
		find $d |grep -v "\." |rsync -a --files-from=- / "$DEST_DIR" || error_msg "Unable to preserve tags" "Warning"
	done
}

############
### main ###
############
#
#

[ "$1" ] || usage
ACTION="$1"

[ "$2" ] || usage
CHBOOT_BASE_DIR="$2"
# i.e. /chboot/lliurex-chboot/srcs/part-roller

case "$ACTION" in
	mkinitrd)
		install_boot_files "$CHBOOT_BASE_DIR/boot"
		;;
	gengrub)
		gen_grub_cfg "$CHBOOT_BASE_DIR"
		;;
	saveusers)
		#USER_LIST_FILE="/usr/share/chboot-part-roller/preserve-user.list"
		FILE_LIST_FILE="./preserve-user.txt"
		echo "Not implemented"
		;;
	savefiles)
		#FILE_LIST_FILE="/usr/share/chboot-part-roller/preserve-file.list"
		FILE_LIST_FILE="./preserve-list.txt"
		preserve_files "$FILE_LIST_FILE" "$CHBOOT_BASE_DIR/data"
		;;
esac

exit 0

